language: python

env:
  global:
    - TX_BRANCH="feature/Transifex"
    - TX_TAG="txpull"
    - TX_COMMIT_TRANSLATIONS=true

install:
  - pip install transifex-client
  
after_success:
  - chmod +x ./.tx.sh
  - ./.tx.sh push
